services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUXT_ENV: "${NUXT_ENV:-dev}"
        NITRO_PORT: "${NITRO_PORT:-3006}"
        NITRO_HOST: 0.0.0.0
    container_name: "vote-fo-welfare-${NUXT_ENV:-dev}"
    restart: unless-stopped
    ports:
      - "3006:3006"
    expose:
      - "3006"
